apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.27.1
#   labels:
#     role: control-plane
# - role: worker
#   image: kindest/node:v1.27.1
#   labels:
#     role: data-plane
#     tier: standard # standard/premium
#     nodetype: generic # generic/gpu
#     disktype: ssd # hdd/ssd
# - role: worker
#   image: kindest/node:v1.27.1
#   labels:
#     role: data-plane
#     tier: standard # standard/premium
#     nodetype: generic # generic/gpu
#     disktype: ssd # hdd/ssd
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
