apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "ingress-ready=true"
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   protocol: TCP
  # - containerPort: 443
  #   hostPort: 443
  #   protocol: TCP
#   labels:
#     role: control-plane
# - role: worker
#   image: kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87
#   labels:
#     role: data-plane
#     zone: az-a
#     tier: standard # standard/premium
#     nodetype: generic # generic/gpu
#     disktype: ssd # hdd/ssd
# - role: worker
#   image: kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87
#   labels:
#     role: data-plane
#     zone: az-b
#     tier: standard # standard/premium
#     nodetype: generic # generic/gpu
#     disktype: ssd # hdd/ssd
# - role: worker
#   image: kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87
#   labels:
#     role: data-plane
#     zone: az-c
#     tier: standard # standard/premium
#     nodetype: generic # generic/gpu
#     disktype: ssd # hdd/ssd
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
