replicas: 1

# If discovery.type in the opensearch configuration is set to "single-node",
# this should be set to "true"
# If "true", replicas will be forced to 1
singleNode: true

opensearchJavaOpts: "-Xmx1024M -Xms512M"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

persistence:
  enabled: false
