datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server
     access: proxy
     isDefault: false
   - name: Loki
     type: loki
     url: http://loki:3100
     access: proxy
     isDefault: false
