daemonset:
  extraEnvs:
  - name: LOGSTASH_HOST
    value: logstash-logstash
  - name: LOGSTASH_PORT
    value: "5044"
  # - name: ELASTICSEARCH_HOST
  #   value: quickstart-es-http
  # - name: ELASTICSEARCH_PORT
  #   value: "9200"
  # - name: NODE_NAME
  #   valueFrom:
  #     fieldRef:
  #       fieldPath: spec.nodeName
  # - name: "ELASTICSEARCH_USERNAME"
  #   valueFrom:
  #     secretKeyRef:
  #       name: elasticsearch-master-credentials
  #       key: username
  # - name: "ELASTICSEARCH_PASSWORD"
  #   valueFrom:
  #     secretKeyRef:
  #       name: elasticsearch-master-credentials
  #       key: password
  filebeatConfig:
    filebeat.yml: |
      # setup.template.name: "myapp"
      # setup.template.pattern: "myapp-*"
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.logstash:
         hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]

      # output.elasticsearch:
      #   host: "${NODE_NAME}"
      #   hosts: '["http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]'
      #   username: "${ELASTICSEARCH_USERNAME}"
      #   password: "${ELASTICSEARCH_PASSWORD}"
      #   protocol: http
      #   ssl.verification_mode: none
      #   ssl.certificate_authorities: []
      #   index: "myapp-%{[agent.version]}-%{+yyyy.MM.dd}"
