# -- Section for crafting Promtails config file. The only directly relevant value is `config.file`
# which is a templated string that references the other values and snippets below this key.
# @default -- See `values.yaml`
config:
  # # -- The port of the Promtail server
  # # Must be reference in `config.file` to configure `server.http_listen_port`
  # # See default config in `values.yaml`
  # serverPort: 3100

  # -- The config of clients of the Promtail server
  # Must be reference in `config.file` to configure `clients`
  # @default -- See `values.yaml`
  clients:
    - url: http://loki:3100/loki/api/v1/push
      tenant_id: tenant-1

  # -- Tenants list to be created on nginx htpasswd file, with name and password keys
  tenants: []
