apiVersion: v1
kind: ConfigMap
metadata:
  name: curator
data:
  curator.yml: |
    elasticsearch:
      client:
        hosts: http://quickstart-es-http:9200
      other_settings:
        username: ${USERNAME}
        password: ${PASSWORD}
  actions.yml: |
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 5 munites
        filters:
        - filtertype: pattern
          kind: prefix
          value: kube-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y-%m-%d'
          unit: days
          unit_count: 90
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curator
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: python:3.12.0-alpine3.17
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - cd && apk add --no-cache curl && curl -L -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py && pip install elasticsearch-curator && curator --config /tmp/curator.yml /tmp/actions.yml
            envFrom:
            - secretRef:
                name: curator
            volumeMounts:
            - name: curator-configmap
              mountPath: /tmp/
          restartPolicy: Never
          volumes:
          - name: curator-configmap
            configMap:
              name: curator
